### ISSUE TITLE
App is unable to read past entries since latest server software update

### ISSUE THREAD

**Issue by P9k** [babybuddy/babybuddy-for-android#74] opened 2024-09-01 07:31 UTC
Since yesterday night, the app is unable to obtain past entries from the database.

When opening the app, there is a message in the bottom saying "Failed to load .... entries", which cycles through everything from "sleep" and "feeding" to "tummy time" etc. (See attached screenshot)

I am on the latest versions for the app (via Google Play Store) and the server software (2.6.0).

The server software was updated yesterday, so I expect the problem to be caused by the update. 

![IMG_20240901_092420](https://github.com/user-attachments/assets/a51160e2-b64c-4cf4-86dc-c6fc84fa3120)

**Comment by MrApplejuice** [comment] 2024-09-01 19:31
Hey! Thank you for reporting... actually very good to hear from users!

Can you try the following: Logout and then login to the server once again? If that fixes it, this is an incarnation of a bug that I just cannot seem to get out of the software. It occurs whenever "something" changes. And I am still not 100% sure what that "something" is.  Changing the server version for testing this did it for me right now, but when I try to observe the issue in debug mode, it is typically already gone again :frowning_face:

**Comment by OneCreek** [comment] 2024-09-01 19:53
> Hey! Thank you for reporting... actually very good to hear from users!
You're welcome 🤗 
> Can you try the following: Logout and then login to the server once again? 
Tried it. Doesn't work... Same issue no matter if logging in again via QR code/API or password.

**Comment by Gu4n** [comment] 2024-09-01 21:50
Thanks for reporting the issue. It also happens on my and my partner's phone. Server is running 2.6.0.

What helped for the time being was downgrading to an older version of the app. I downloaded the 2.1.0 version from the GitHub releases and this versions works fine on both phones. I haven't tried any other version.

**Comment by MrApplejuice** [comment] 2024-09-01 21:56
> it's great to see there is still support/active development. Bought the app just last week to support:)

Huge thanks for that and sorry that it immediately fell over. I was able to re-create the issue somehow, however, the procedure to create this is relatively iffy and not easy to reproduce... still progress, I think!:

And just to be clear: **_If you want a refund, I can certainly arrange that._** Please contact me on the email that is listed on the google-play store page for that!

<img src="https://github.com/user-attachments/assets/e71dd4ee-6ca2-462e-a61c-54700105961d" width="200px">

------------------

I just saw @Gu4n 's suggestion and that, of course, is a possibility! Nice to see that you found a solution that works for you. But it seems that this needs to get a high priority now, I hope to have a fix soon!

**Comment by MrApplejuice** [comment] 2024-09-02 08:24
Got 2x more anonymous in-app messages about this issue.

**Comment by MrApplejuice** [comment] 2024-09-02 08:36
## Update

I have created an experimental patch, but I am not too confident that it will work. I bundled the patch together with the almost ready interface change that will be part of release 2.4.0. Not ideal, but was quicker to test for me this way.

You could really help me by trying it out by installing the new test-release: https://github.com/babybuddy/babybuddy-for-android/releases/tag/v2.4.0a

There will also be a open testing branch on google play, but that one is currently waiting for a review by google...

**If it still does not work**, I would like to ask you to send me the logs that you can copy from inside the "Test release", by accessing the main menu and selecting the "Export Debug Logs" option:

![image](https://github.com/user-attachments/assets/f399ddb1-fc8b-44b3-a99a-b45e16e68335)

You can review the data you send me there, I did my best to only create a somewhat anonymous log, but I cannot guarantee that it is fully anonymous. If you want to get the logs to me directly and conveniently, you can use the "Contact Developer" option on that very same page. If you want me to be able to identify which reports comes from you, add your username in the message!

**_Feedback would be very welcome_**

**Comment by Gu4n** [comment] 2024-09-02 09:14
Likewise, works for me, too! Thanks!

**Comment by OneCreek** [comment] 2024-09-02 09:57
> Got 2x more anonymous in-app messages about this issue.

One from me;)
Looking forward to the beta channel in Google play.
No intention to refund by the way;)

**Comment by MrApplejuice** [comment] 2024-09-02 18:02
Awesome, thanks for the feedback and updates on here! Big help! This needs to be pushed online ASAP then though it might take another day or two to get this update truly live.

If you want to try the open test track on the play store in the mean time, you can use this link: 

https://play.google.com/apps/testing/eu.pkgsoftware.babybuddywidgets

**Closed** 2024-09-02 20:43 UTC
Labels: bug

**Comment by MrApplejuice** [comment] 2024-09-03 08:51
I now shipped the actual release of version 2.4.0. It should be live on the play store in a few hours. Thanks again to you all for helping on reporting and fixing the issue!
