### ISSUE TITLE
Diaper color selection sub menu

### ISSUE THREAD

**Issue by OneCreek** [babybuddy/babybuddy-for-android#75] opened 2024-09-02 10:31 UTC
It would be great to have a selection similar to which breast side after choosing breast feeding to also choose the color after choosing solid in diaper change.

**Comment by MrApplejuice** [comment] 2024-09-02 20:34
Hey! I have to close this as a duplicate of #42. Definitely, on "the list" though!

**Closed by MrApplejuice** 2024-09-02 20:34 UTC
